/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-121159-g0bd5a7d371-20250921"
#endif /* AVUTIL_FFVERSION_H */
